README.md

`-action` has been added to the end of this repo name after discussion. Also, fix a few instances I missed of _Lacework Code Analysis_ to _Lacework Code Security_ which is the name Marketing has approved.

chore: Some renaming tweaks to documentation

---

action.yaml

We're making a lot of API calls to install the components which is resulting in us hitting some rate limits. Let's store these in the [Actions cache](https://github.com/actions/cache) for the repository instead of fetching them on every run, which should drastically reduce the number of calls we're making as well as make things quicker since downloading from the repo cache should be faster than requesting a download from our API server and then downloading from an S3 bucket.
The downside of this is it circumvents checking the feature flag, so if we opt out a user then they'll still be able to continue running things. To avoid this being perpetually true, include the current day in the cache key so that once a day we do the download via the normal route. Of course also include the current …

Cache installation of components to reduce API calls

---

action.yaml
src/index.ts
src/tool.ts

Notably, sast and sca now support telemetry and the flag `--deployment`

bump components version

---

src/util.ts

Print the content of stderr (e.g., all logs) even if debug is `false`
This helps understanding in scenario like https://github.com/lacework/code-security-action/actions/runs/5044906503/attempts/1 where, before this PR, we wouldn't have been able to see any logs

print stderr at every run

---

action.yaml

In particular, this version should start populating committer information and CI job information for the UI to use.

chore: Bump SCA to 0.0.46

---

action.yaml

This version fixes the sarif format generated by SCA

chore: Bump SCA to 0.0.47

---

action.yaml

This version supports offline bazel golang scanner, better telemetry and bug fixes.

chore: Bump SCA to 0.0.48

---

.github/workflows/integration-test.yml
action.yaml
src/index.ts

The `--classes` option SAST which was previously accepting a directory or a JAR file has now been replaced by a more generic `--classpath` option which is intended to be the standard Java classpath containing all the classes including the dependencies or self-contained JAR or WAR files with nested JAR dependencies.
The main goal is to make the SAST API more generic and able to work in the same way with Mariana Trench and Infer.
This changes the public API of the action code so we will need to create a different release tag to migrate the place where this code is used progressively.

chore: bump SAST to 0.0.46

---

.github/workflows/update-tag.yml

This will save us having to manually run this after a merge to `main` in order to get things actually released.

chore: Automate upgrading of v1 tag

---

src/index.ts
src/tool.ts
src/util.ts

I believe part of the reason we're causing errors when we call a command that produces a lot of output is that we try to dump the whole output from the command in one go rather than streaming it so it can be bufferred out in a sensible manner. This PR addresses that, and should allow us to use `debug` mode in more scenarios.

chore: Improve how we handle spawning commands

---

action.yaml
src/index.ts
src/post.ts
src/util.ts

In certain scenarios, we've observed not reaching our telemetry code because we fail with an error so catastrohpic that the runner crashes. This PR adds a post-run step where we can at least observe these errors and send back _something_ to say they happened even though we'll have lost the full context so won't be able to send back details of what the error was.

feat: Log catastrohpic errors to our telemetry

---

action.yaml

This should make workflows only using one of the tools a little bit quicker, and also avoids issues for customers who are only feature flagged for one tool.

feat: Only install the tools we're actually using

---

action.yaml
package-lock.json
package.json
src/actions.ts
src/index.ts
src/keys.ts

Now that SCA has the ability to verify commit signatures, let's leverage this by actually downloading all the GPG keys of users in the same GitHub org as the repository and passing these to SCA as keys that it should trust when verifying signatures.

feat(COD-1124): Trust keys of users in the same org as the repo

---

src/actions.ts
src/post.ts

Currently, we report an `Unknown failure` is our Action started running but didn't finish and we failed to otherwise report telemetry. This was added to catch issues like OOMs which might result in us not getting a chance to report telemetry in the normal way. However, we should exclude casees where the run was actually deliberately cancelled by the user from this code path. This PR adds that.

fix: Don't report unknown failure on cancelled runs

---

action.yaml

The SAST release have been fixed now. This should be good to go.

chore: bump SAST to 0.0.50

---

.github/workflows/integration-test.yml
action.yaml

Make the action compatible with macOS and enable the integration tests for both platforms. The main thing to fix was to install `coreutils` on macOS in order to get `gdate` and `md5sum` and rely on the version of `yq` from the system instead of the one from `pip` since `pip` is installing incompatible versions on Linux and macOS.

test(COD-1317): run the tests on Linux and macOS

---

.github/workflows/integration-test.yml
action.yaml

Reverts lacework/code-security-action#80
It seems that the SCA test on macOS is failing randomly: https://github.com/lacework/code-security-action/actions/runs/5705756521/job/15460771065#step:5:201

Revert "test(COD-1317): run the tests on Linux and macOS"

---

action.yaml

It turns out that when we cache the download of the SAST and SCA binaries, we fail to account for the fact that these binaries are different between OSes and architectures. So we may try to use a Mac binary on Linux or vice versa which of course won't work. Let's include the OS and architecture in the cache key.

fix(COD-1498): Include OS and architecture in binary cache key

---

action.yaml

Revert version of SCA to v0.0.57 due to an increase of run-time of sca

chore: Revert version of SCA to v0.0.57

---

.github/workflows/integration-test.yml
src/index.ts

in a prev PR the output format changed to a folder containing the sarif and the lwjson format of the SBOM and that broke workflows relying on the output being just a sarif file.

COD-1580: Problem with sarif output

---

src/tool.ts

Prior parsing had bugs because of the format of the package-lock.json file name.

Autofix - better parsing of modified files

---

.github/workflows/integration-test.yml

So we get more info out of the CLI and can debug the intermittent macOS errors.

chore: Set `DEBUG` in integration tests

---

action.yaml

The latest release is failing because of [malformed SARIF file](https://github.com/lacework/rainbow/actions/runs/6070172340/job/16465742141#step:9:281). This PR reverts SAST to the previous release.

chore: revert to last working release

---

README.md

With 22.04, we sometimes failed to report telemetry due to this known issue: https://github.com/actions/runner-images/issues/6709
Let's advise customers to use 20.04 instead - it should work just as well and is better for our observability.

chore: Recommend Ubuntu 20.04 instead of 22.04

---

action.yaml
src/index.ts
src/keys.ts
src/telemetry.ts

Follow-up from [this](https://github.com/aleftik/microservices-demo/actions/runs/6202190073/job/16840427733#step:3:424) failure being encountered.
Failures in this code shouldn't be fatal so let's just log a warning, report them in our telemetry and continue. Also, make sure to always set up the version of Node we need which may have been the cause of the problem observed (our action was being run on a self-hosted runner with an old version of Node).

fix: Make downloading of keys more robust

---

action.yaml
src/keys.ts

A few fixes:
1. Add `rm -rf ../lacework-code-security` to make sure we overwrite previous versions of the action that may still be present on self-hosted runners, ensuring we actually always run the latest code. (This was the reason the `catch` added in the previous PR wasn't working.)
2. Move `mkdirSync` to higher up, as apparently on self-hosted runners the code in `restoreCache` fails upon trying to create this.
3. Downgrade the `warning` if we fail to an `info` message, since this is expected to happen when the repo is a personal one rather than an org, so warning is a bit too noisy.
Sample run after these changes on the previously problematic repo: https://github.com/aleftik/microservices-demo/actions/runs/6246738738

fix(COD-1811): Fix no such file or directory error

---

action.yaml
src/index.ts

The SAST component now runs QuickSAST by default and relies on the value of the Java classpath to enable DeepSAST. This will allow the GitHub action code to run QuickSAST by default if the classpath is not specified. See https://github.com/lacework-dev/codesec/pull/187.

feat(COD-1929): change the default value for the Java classpath

---

src/index.ts

Detect if the GitHub action has been triggered in a PR and provide branch information to CodeSec tools.
Tested in https://github.com/lacework-dev/code-analysis-test-repo/actions/runs/7413026134/job/20171094879?pr=305#step:5:423  https://github.com/lacework-dev/code-analysis-test-repo/actions/runs/7413026134/job/20171094615?pr=305#step:5:422

fix(COD-2376): Error retrieving branch in GitHub PRs

---

src/tool.ts

This PR updates tool.ts to accomodate a change in the autofix output done in this other PR: https://github.com/lacework-dev/codesec/pull/433

Remove the Ariadne name from the Autofix output

---

.github/workflows/integration-test.yml

Before this PR, the SCA integration tests was relying on running `dotnet publish` before running SCA. I don't know if this is the expected behavior. It may be preferable for the integration tests to be "buildless" since this is the user workflow we mostly intend to promote.
The actual differences we get after removing the `dotnet publish` build steps are here: https://gist.github.com/jeremydubreil/d37158848e508cc4851331771de137a3

test(COD-2736): remove unused dotnet step

---

src/util.ts

Autofix does fix all the vulnerabilities, regardless of whether they are newly introduced, so we don't want to run sca on 'old' to avoid concurrency issues due to autofix generating the same branch multiple times

skip autofix on 'old' target

---

action.yaml

Enable debug logging on the CLI as well (when debug is set). Add a component donwload timeout to prevent hung integration tests during download failure.

chore(GROW-2895): add cli debug logging and download timeout

---

.lacework/codesec.yaml
README.md
action.yaml
src/index.ts
src/post.ts
src/util.ts

These options are not used anymore.
Tested here:
-  scheduled run: https://github.com/lacework-dev/WebGoat/actions/runs/8751365497
- PR workflow: https://github.com/lacework-dev/WebGoat/actions/runs/8751365734

chore(COD-2736): remove deprecated options

---

action.yaml

This option has been deprecated for a while so removing it should be safe now.

docs(COD-3542): remove the deprecated tools option

---

.lacework/codesec.yaml

These config file is not needed anymore.

chore(COD-3829): delete the Lacework codesec config file

---

.github/workflows/integration-test.yml

The SCA scan now finds one less finding than before on the test code.

test(COD-4237): only check if the list of expected is not 0

---

action.yaml
src/index.ts

There is no reason for the `--secret` to be hard-coded in the GitHub Actions code. This means the option can never be disabled since CLI options have the highest priority.

chore(COD-4237): remove the hard-coded --secret option

---

.github/workflows/integration-test.yml
action.yaml

This will let the Lacework CDK use the latest SCA release available for the associated account.
Tested in https://github.com/lacework-dev/WebGoat/pull/105#issuecomment-2545839593

feat(COD-4237): remove the SCA version check

---

.github/workflows/update-tag.yml
README.md

Updating the documentation while I am looking into this code.

docs(COD-4237): update the documentation

---

.github/workflows/integration-test.yml
action.yaml
package-lock.json
package.json
src/actions.ts
src/index.ts

The action `download-artifact@v3` is deprecated and this make the GitHub action code to fail.
Update the GitHub action code to the latest version of the `actions/artifact` library.
The integration tests are passing now and on several platforms.
Tested on a PR [here](https://github.com/lacework-dev/WebGoat/pull/118) and generated this [PR comment](https://github.com/lacework-dev/WebGoat/pull/118#issuecomment-2829617252).

fix(COD-4320): update @actions/artifact to version 2.3.2

---

package-lock.json

Update `package-lock.json` with a more recent version of `npm` to address the warnings we get when running the action: https://github.com/lacework-dev/codesec/actions/runs/14725778496/job/41327995882?pr=1241#step:4:121
No functional changes intended.

fix(COD-4320): update out-of-date lock file

---

action.yaml

Address these [warning messages](https://github.com/lacework/services/actions/runs/15137572145/job/42552945155#step:4:119) raised because the version of Node.js is too old when scanning PRs.

chore(COD-5174): use Node.js version 18

---

src/index.ts
src/tool.ts

Printing the full list of SCA findings in blowing up the GitHub action output on large repositories. This prevents us from looking at the logs we get from the SCA runs.

fix(COD-5581): no longer print the list of findings in the action output
