lacework/code-security-action

package-lock.json
package.json
src/actions.ts
src/index.ts

Missed in previous PRs that did the renaming.

chore: A few more renamings

---

action.yaml
src/index.ts

This should get us source control references.

chore: Run SCA in git mode

---

action.yaml

chore: Bump version of SCA to v0.0.50

---

action.yaml

chore: Bump version of SCA to v0.0.52

---

action.yaml

chore: Bump version of SCA to v0.0.53

---

package-lock.json
package.json
src/actions.ts

Prompted by seeing [this](https://github.com/lacework-dev/railgun/actions/runs/5537080731/jobs/10105528237#step:2:432) run in our new telemetry for this Action. It looks like there was a failure with the API to post a comment at least in that case. Let's set a timeout of 30 seconds on requests and retry them up to three times. This should hopefully make this more robust.

feat: Add custom timeout and retrying to API calls

---

action.yaml

chore: Bump version of SCA to v0.0.54

---

.github/workflows/integration-test.yml

Re-enable the integration tests on macOS.

test(COD-1317): run the tests on Linux and macOS

---

action.yaml

chore: Bump version of SCA to v0.0.56

---

action.yaml

chore: Bump version of SCA to v0.0.57

---

action.yaml

chore: Bump version of SCA to v0.0.59

---

action.yaml

chore: Bump version of SCA to v0.0.60

---

action.yaml

chore: Bump version of SCA to v0.0.61

---

action.yaml

chore: Bump version of SCA to v0.0.62

---

action.yaml

chore: Bump version of SCA to v0.0.63

---

action.yaml
sample-repo/src/main/java/hello/Library.java

So that it passes the current set of filters
https://lacework.atlassian.net/browse/COD-1662

bug(COD-1662): make vuln in sample repo about file access

---

action.yaml

chore: Bump version of SAST to v0.0.53

---

action.yaml

chore: Bump version of SCA to v0.0.64

---

action.yaml

chore: Bump version of SCA to v0.0.65

---

action.yaml

chore: Bump version of SAST to v0.0.54

---

action.yaml

chore: Bump version of SCA to v0.0.66

---

action.yaml

chore: Bump version of SCA to v0.0.67

---

action.yaml

chore: Bump version of SCA to v0.0.68

---

action.yaml

chore: Bump version of SCA to v0.0.69

---

action.yaml

chore: Bump version of SCA to v0.0.70

---

action.yaml

chore: Bump version of SAST to v0.0.55

---

action.yaml

chore: Bump version of SCA to v0.0.71

---

src/tool.ts

Added telemetry regarding the number of PRs, time spent for autofix and time spent calling GitHub API.
Link to results: https://ui.honeycomb.io/lacework/datasets/lacework-cli-prod/result/eo7Z5vt96k

Autofix-Telemetry

---

action.yaml

chore: Bump version of SCA to v0.0.72

---

src/index.ts

Use `lacework sca scan` instead of `lacework sca git`
It will be manually merged when `sca-v0.0.73` will be released and if the tests pass.

feat(COD-1821): Unified scan command

---

action.yaml
src/index.ts

chore: Bump version of SCA to v0.0.73

---

action.yaml

chore: Bump version of SCA to v0.0.74

---

action.yaml

chore: Bump version of SCA to v0.0.75

---

action.yaml

chore: Bump version of SAST to v0.0.56

---

action.yaml

chore: Bump version of SCA to v0.0.76

---

action.yaml

chore: Bump version of SCA to v0.0.77

---

action.yaml

chore: Bump version of SCA to v0.0.78

---

action.yaml
src/index.ts
src/util.ts

Enable an optional flag `dynamic` to integrate SCA results with dynamic data, such as package activity

feat(COD-2102): Add an option to use CAA data

---

action.yaml

chore: Bump version of SCA to v0.0.79

---

action.yaml

chore: Bump version of SCA to v0.0.80

---

action.yaml

chore: Bump version of SAST to v0.0.57

---

action.yaml

chore: Bump version of SAST to v0.0.58

---

action.yaml

chore: Bump version of SAST to v0.0.59

---

action.yaml

chore: Bump version of SCA to v0.0.81

---

action.yaml

chore: Bump version of SCA to v0.0.82

---

action.yaml

chore: Bump version of SAST to v0.0.61

---

action.yaml

chore: Bump version of SCA to v0.0.83

---

action.yaml

chore: Bump version of SCA to v0.0.84

---

action.yaml

chore: Bump version of SAST to v0.0.62

---

action.yaml

chore: Bump version of SCA to v0.0.85

---

action.yaml

chore: Bump version of SCA to v0.0.86

---

action.yaml

chore: Bump version of SAST to v0.0.63

---

.github/workflows/integration-test.yml
action.yaml

chore: Bump version of SCA to v0.0.87

---

action.yaml

chore: Bump version of SCA to v0.0.88

---

action.yaml

chore: Bump version of SCA to v0.0.89

---

src/lw-json.ts
src/tool.ts

adapt the code to the new LwJson format which now supports Ariadne recommendations
Tested on https://github.com/lacework-dev/code-analysis-test-repo/pull/307

support ariadne recommendations

---

action.yaml

chore: Bump version of SCA to v0.0.90

---

src/tool.ts

Tested on https://github.com/lacework-dev/code-analysis-test-repo/pull/312

support ariadne version graph

---

action.yaml

chore: Bump version of SAST to v0.0.64

---

action.yaml

chore: Bump version of SCA to v0.0.91

---

action.yaml

chore: Bump version of SCA to v0.0.92

---

action.yaml

chore: Bump version of SAST to v0.0.65

---

action.yaml

chore: Bump version of SAST to v0.0.66

---

README.md

Remove SAST option from readme

---

action.yaml

chore: Bump version of SCA to v0.0.94

---

action.yaml

chore: Bump version of SAST to v0.0.69

---

action.yaml

chore: Bump version of SCA to v0.0.95

---

.github/workflows/integration-test.yml
sample-repo/src/main/java/hello/Application.java

This test will be useful as we enable the `sca scan --fast` option of SCA. The ProSAST example is not useful here.

test(COD-2736): use FAST example for the integration test

---

action.yaml

chore: Bump version of SCA to v0.0.96

---

action.yaml

chore: Bump version of SAST to v0.0.70

---

action.yaml

chore: Bump version of SCA to v0.0.97

---

action.yaml

chore: Bump version of SCA to v0.0.98

---

action.yaml

chore: Bump version of SCA to v0.1.0

---

action.yaml

chore: Bump version of SAST to v0.0.71

---

action.yaml

chore: Bump version of SCA to v0.1.1

---

action.yaml

chore: Bump version of SCA to v0.1.2

---

.github/workflows/integration-test.yml
action.yaml
src/index.ts

This code is not used anymore.
Tested here: https://github.com/lacework-dev/WebGoat/actions/runs/8687252143

chore(COD-2736): remove the remaining SAST-related code

---

action.yaml

chore: Bump version of SCA to v0.1.3

---

action.yaml

chore: Bump version of SCA to v0.1.4

---

action.yaml

chore: Bump version of SCA to v0.1.5

---

action.yaml

chore: Bump version of SCA to v0.1.6

---

action.yaml

chore: Bump version of SCA to v0.1.7

---

.github/workflows/integration-test.yml
action.yaml

chore: Bump version of SCA to v0.1.9

---

action.yaml

chore: Bump version of SCA to v0.1.10

---

action.yaml

chore: Bump version of SCA to v0.1.11

---

action.yaml

chore: Bump version of SCA to v0.1.12

---

action.yaml

chore: Bump version of SCA to v0.1.13

---

action.yaml

chore: Bump version of SCA to v0.1.14

---

action.yaml

chore: Bump version of SCA to v0.1.15

---

action.yaml

chore: Bump version of SCA to v0.1.16

---

action.yaml

chore: Bump version of SCA to v0.1.17

---

.github/workflows/integration-test.yml
.vscode/settings.json
action.yaml

chore: Bump version of SCA to v0.1.18

---

action.yaml

chore: Bump version of SCA to v0.1.19

---

action.yaml

chore: Bump version of SCA to v0.1.20

---

action.yaml

chore: Bump version of SCA to v0.1.21

---

action.yaml

chore: Bump version of SCA to v0.1.22

---

action.yaml

chore: Bump version of SCA to v0.1.23
